name: 'Code Coverage'
on:
    pull_request:
        branches: '*'

jobs:
    check-coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v3
            - uses: artiomtr/jest-coverage-report-action@v1.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80
                  
