name: Lint source code
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Print Node Version
        run: node --version
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - name: Build ncc 
      - run: echo "123" > ./dist/index.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Kevin Bronsdijk
          author_email: mail@example.com
          message: 'Your commit message'
          add: './dist/*.*'
