name: Node.js CI

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    types: [ opened ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Print Node Version
      run: node --version
    - name: Install Dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: artiomtr/jest-coverage-report-action@v1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
