name: Lint source code
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Print Node Version
        run: node --version
      - name: Install Dependencies
        run: npm ci
      - name: Run ncc build
        run: npm run-script buildncc
      - run: mkdir -p ./dist
      - run: echo "123" > ./dist/index.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Kevin Bronsdijk
          author_email: bronsdijk@bronsdijk.com
          message: 'Auto update of ncc build artifact'
          add: './dist/index.js'
