name: 'Package'
on:
  push:
    branches:
    - main

jobs:
  build:
    name: create ncc artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run buildncc
      - run: yarn run buildnccroot
      - run: mkdir -p ./github/actions/nugetprerelease/dist
      - run: mkdir -p ./dist
      - run: cp ./.github/actions/nugetprerelease/action.yml ./action.yml
      - name: commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Kevin Bronsdijk
          author_email: bronsdijk@bronsdijk.com
          message: 'Auto update of ncc build artifact'
          add: "['./.github/actions/nugetprerelease/dist/*', './dist/*', './action.yml']"
