name: Lint source code
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "123" > ./test.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Kevin Bronsdijk
          author_email: mail@example.com
          message: 'Your commit message'
          add: './test.js'
