name: 'Pull CI'

on:
  pull_request:
    branches: '*'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: use node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: run eslint
      run: yarn run lint
    - run: yarn test
    - run: yarn run buildncc
    - name: action end-to-end test
      uses: ./.github/actions/nugetprerelease
      id: nugetprerelease
      with:
        solution-file-name:  test.sln
        solution-path: ./tests/data/
    - run: echo "result ${{ steps.nugetprerelease.outputs.found-pre-release }}"
