name: 'Pull CI'

on:
  pull_request:
    branches: '*'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: use node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: npm install '@actions/core
    - name: install dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm install -g eslint
    - name: Run ESLint
      run: eslint .
    - run: npm test
    - run: npm i -g @vercel/ncc
    - name: run ncc build
      run: npm run-script buildncc
    - name: action end-to-end test
      uses: ./.github/actions/nugetprerelease
      id: nugetprerelease
      with:
        solution-file-name:  test.sln
        solution-path: ./tests/data/
    - run: echo "result ${{ steps.nugetprerelease.outputs.found-pre-release }}"
